---
title: "BFI_MI_1702_data"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(pander)
library(magrittr)
panderOptions("table.split.table", Inf)
knitr::opts_chunk$set(echo = TRUE)
```

### Data

```{r, xlsx}
library(xlsx)
options(width = 180)

class_roll <- readRDS("class_id_group.RDS")
class_roll %<>%
  `names<-`(c("ID", "Group"))
names(class_roll) <- c("ID", "Group") #같다

BFI <- "../data/BFI.xlsx" %>% 
  read.xlsx(sheetIndex = 1, 
            startRow = 2, endRow = 26, 
            colIndex = 1:13, 
            header = TRUE, 
            encoding = "UTF-8",
            stringsAsFactors = FALSE)
# BFI <- read.xlsx("../data/BFI.xlsx",sheetIndex = 1....)

names(BFI) %<>%
  `[<-`(1, "ID")
# names(BFI)[1] <- "ID" 첫번째 자리에 넣어라 
BFI %<>%
  `names<-`(c("ID", "E1", "A1", "O1", "C1", "N1", "E2", "A2", "O2", "C2", "N2", "O3", "A3"))
#names(BFI) <- (c("ID", "E1", "A1", "O1", "C1", "N1", "E2", "A2", "O2", "C2", "N2", "O3", "A3"))
BFI$ID %<>%
  as.character
#BFI$ID <- as.character(BFI$ID)
BFI %>% 
  head %>%
  kable
#kable(head(BFI))
# pander(head(BFI))
MI <- "../data/MI.xlsx" %>%
  read.xlsx(sheetIndex = 1, 
            startRow = 2, endRow = 182, 
            colIndex = 1:57, 
            header = TRUE, 
            encoding = "UTF-8",
            stringsAsFactors = FALSE)
MI %<>%
  `names<-`(c("ID", paste0("Q", 1:56)))
#paste0 글자를합침ex q1,q2,q3,q4,q5.....
# names(MI) <- c("ID", paste0("Q", 1:56))
MI$ID %<>% 
  as.character
MI$ID <- as.character(MI$ID)
kable(head(MI[1:15]))
kable(head(MI[c(1, 16:29)]))
kable(head(MI[c(1, 30:43)]))
kable(head(MI[c(1, 44:57)]))
lapply(list(c(1:15), c(1, 16:29), c(1, 30:43), c(1, 44:57)), 
       function(x) kable(head(MI[x])))
# lapply 리스트를 만들어준다 자료형이 문자, 숫자 등이 섞여서 만들어도 만들어진다
```

### Save Data

```{r, save.image}
save.image("./BFI_MI_1702.RData")
```

