```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

### Data

```{r, data}
class_roll <- read.csv("../data/class_roll02.csv", 
                       skip = 1,
                       colClasses = rep("character", 6), 
                       stringsAsFactors = FALSE)
class_roll <- class_roll[, -c(1:2, 8)]
names(class_roll) <- c("dept", "id", "name", "year", "e.mail", "cell.no")
```

### Names

```{r, name}
not3.ind <- which(nchar(class_roll$name) != 3)
not3.ind
class_roll$name[not3.ind] <- paste(substr(class_roll$name[not3.ind], 1, 1), "ㅇㅇ", sep = "")
class_roll$name[not3.ind]
names.split <- sapply(class_roll$name, function(x) unlist(strsplit(x, split = "")))
kable(names.split[, 1:10])
names.split[2:3, ] <- rep("ㅇ", 2)
class_roll$name <- apply(names.split, 2, paste, collapse = "")
kable(class_roll)
```

### Cell Phone Numbers

```{r, cell.no}
cell.na <- class_roll$cell.no == ""
class_roll$cell.no[cell.na] <- "NA-NA-NA"
cell.split <- sapply(class_roll$cell.no, function(x) unlist(strsplit(x, split = "-")))
kable(cell.split[, 1:5])
cell.split[3, ] <- "xxxx"
class_roll$cell.no <- apply(cell.split, 2, paste, collapse = "-")
kable(class_roll)
```

### e-mail


```{r, e_mail}
e.mail.na <- class_roll$e.mail == ""
class_roll$e.mail[e.mail.na] <- "NA@NA"
email.split <- sapply(class_roll$e.mail, function(x) unlist(strsplit(x, split = "@")))
kable(email.split[, 1:5])
email.split[1, ] <- "user_name"
class_roll$e.mail <- apply(email.split, 2, paste, collapse = "@")
kable(head(class_roll))
```

<!--
```{r, save}
write.table(class_roll, file ="../data/class_roll_masked.txt")
save.image("../R/class_roll_170303_data_masked.RData")
```
-->