---
title: "Red and Black : id Masked"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(xlsx)
```

### Data

```{r, data}

class_roll <- read.xlsx("./data/응용R2분반.xlsx", 
                        sheetIndex = 1, 
                        startRow = 2, 
                        endRow = 28, 
                        colIndex = c(4,5,7,9), 
                        colClasses = rep("character", 4), 
                        encoding = "UTF-8", 
                        stringsAsFactors = FALSE)

names(class_roll) <- c("id", "name", "email", "cell_no")
```

### Randomization

```{r, randomization}
set.seed(1)
N <- nrow(class_roll) #class_roll의 케이스 갯수를 저장한다
class_roll$group <- sample(1:N) %% 7 + 1
#2로 나눈 나머지 0또는1에 1을 더하면 1또는2가 나오게된다
#즉 '1그룹'과 '2그룹'으로 나눈다
class_roll$group <- factor(class_roll$group, 
                           labels = c("1team","2team","3team","4team","5team","6team","7team"))

#class_roll의 그룹을 1= red 2=black으로 이름을 붙인다
#red_id <- which(class_roll$group == "Red")
#라벨이 red인 애들을 red_id로 정의해준다
#black_id <- which(class_roll$group == "Black")
#라벨이 black인 애들을 black_id로 정의해준다


```

### 학번

```{r, id}
ID_16 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2016, 
                       "younger_16", "older_16"), 
                levels = c("younger_16", "older_16"))
#substr class_roll$id에서 1~4번째만 추출한다 ex)2014,2015,2016...4번째자리만
#ifelse 추출한 4자리숫자가 2016보다 크거나 같으면 younger_16으로 아니면 older_16으로
#큰 틀에서 factor로 지정했기 때문에 1번째는 younger로 2번째는 older로 이름붙인다
kable(table("그룹" = class_roll$group, 
            "16학번 기준" = ID_16))
ID_15 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2015, 
                       "younger_15", "older_15"), 
                levels = c("younger_15", "older_15"))
kable(table("그룹" = class_roll$group,
            "15학번 기준" = ID_15))
ID_14 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2014, 
                       "younger_14", "older_14"), 
                levels = c("younger_14", "older_14"))
kable(table("그룹" = class_roll$group,
            "14학번 기준" = ID_14))
ID_13 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2013, 
                       "younger_13", "older_13"), 
                levels = c("younger_13", "older_13"))
kable(table("그룹" = class_roll$group,
            "13학번 기준" = ID_13))
```

<!--
### 학번 홀짝

```{r, odd or even}
odd.even <- as.numeric(class_roll$id) %% 2
kable(table("odd_even" = odd.even, "Group"= class_roll$group))
```
-->

### email 서비스업체

```{r, e_mail}
email_list <- strsplit(class_roll$email, "@", fixed = TRUE)
#리스트 형식으로 저장된다
# @를 기준으로 잘랐을때 kkm5022 naver.com이면 2번째꺼를 뽑아라

mail_com <- sapply(email_list, `[`, 2)
kable(table("그룹" = class_roll$group,
            "e-mail" = mail_com))
```

### 성씨 분포

```{r, name}
f_name <- substring(class_roll$name, 
                    first = 1, last = 1)
#처음(성) 마지막(성) 처음이자 마지막 글자(첫번째글자만) 잘라서 저장한다
kable(table("Group" = class_roll$group,
            "Family Name" = f_name)) #안먹는다??
#kable(table(class_roll$group,f_name))
```

### 많이 나오는 성씨

```{r, frequent names}
f_name_f <- factor(ifelse(f_name %in% c("김", "이", "박"), 
                          f_name, "기타"), 
                   levels = c("김", "이", "박", "기타"))


# A %in% B A가 B안에 포함이 되는가?
str(f_name_f)
kable(table("Group" = class_roll$group, 
            "Family Name" = f_name_f))
```

### 전화번호의 분포

```{r}
cell_numbers <- sapply(substr(class_roll$cell_no, start = 5, stop = 8), 
                       as.numeric)
# cut_label <- c("1000~1999", "2000~2999", "3000~3999", "4000~4999", "5000~5999", "6000~6999",
#                "7000~7999", "8000~8999", "9000~9999")
cut_label <- paste(paste0(1:9, "000"), paste0(1:9, "999"), sep = "~")
kable(t(table(cut(cell_numbers, 
                  labels = cut_label, 
                  breaks = seq(1000, 10000, by = 1000)))))
hist(cell_numbers)
chisq.test(table(cut(cell_numbers, 
                  labels = cut_label, 
                  breaks = seq(1000, 10000, by = 1000))))


class_roll
```



### 출석부에서 8명 비복원 랜덤 표집

```{r, colleges}
# set.seed(1)
kable(class_roll[sample(1:N, size = 8), ])
```

<!--
<P style = "page-break-before:always">
-->

### `set.seed()` 의 용법
난수를 뽑았을 때 그 난수가 바뀌지 않도록 저장하는것
예를 들면 set.seed(1)이면 1번사물함에 난수를 저장한다

`set.seed()`를 이용하면 랜덤넘버에 의존하는 실험을 재현할 수 있다. 
다음 코드를 반복 수행하거나 다른 사람들의 수행결과와 비교해 보라.

세 결과가 모두 다른 경우

```{r}
sample(1:6, size = 2)
sample(1:6, size = 2)
sample(1:6, size = 2)
```

 세 번의 수행 결과가 똑같이 반복되는 경우

```{r}
set.seed(1) # 1번사물함에 3개의 난수를 저장 
sample(1:6, size = 2)
sample(1:6, size = 2)
sample(1:6, size = 2) 
set.seed(1) #1번사물함에 저장한 난수를 불러온다 
sample(1:6, size = 2)
sample(1:6, size = 2)
sample(1:6, size = 2)

#sample() 비복원추출, 복원추출 둘다 가능
sample(1:6, size = 2, replace = T) #복원추출
```

동일한 결과를 반복적으로 얻는 경우

```{r}
set.seed(1)
sample(1:6, size = 2)
set.seed(1)
sample(1:6, size = 2)
set.seed(1)
sample(1:6, size = 2)
```

<!--
```{r, save}
save.image("../R/red_and_black_data_masked.RData")
```
-->